CREATE TABLE [dbo].[mt5_orders] (
  [Order] [bigint] NOT NULL,
  [TIMESTAMP] [bigint] NOT NULL,
  [ExternalID] [nvarchar](32) NOT NULL,
  [Login] [bigint] NOT NULL,
  [Dealer] [bigint] NOT NULL,
  [Symbol] [nvarchar](32) NOT NULL,
  [Digits] [int] NOT NULL,
  [DigitsCurrency] [int] NOT NULL,
  [ContractSize] [float] NOT NULL,
  [State] [int] NOT NULL,
  [Reason] [int] NOT NULL,
  [TimeSetup] [datetime] NOT NULL,
  [TimeExpiration] [datetime] NOT NULL,
  [TimeDone] [datetime] NOT NULL,
  [Type] [int] NOT NULL,
  [TypeFill] [int] NOT NULL,
  [TypeTime] [int] NOT NULL,
  [PriceOrder] [float] NOT NULL,
  [PriceTrigger] [float] NOT NULL,
  [PriceCurrent] [float] NOT NULL,
  [PriceSL] [float] NOT NULL,
  [PriceTP] [float] NOT NULL,
  [VolumeInitial] [bigint] NOT NULL,
  [VolumeCurrent] [bigint] NOT NULL,
  [ExpertID] [bigint] NOT NULL,
  [PositionID] [bigint] NOT NULL,
  [PositionByID] [bigint] NOT NULL,
  [Comment] [nvarchar](32) NOT NULL,
  [ActivationMode] [int] NOT NULL,
  [ActivationTime] [bigint] NOT NULL,
  [ActivationPrice] [float] NOT NULL,
  [ActivationFlags] [int] NOT NULL,
  CONSTRAINT [PK_mt5_orders] PRIMARY KEY CLUSTERED ([Order]) WITH (FILLFACTOR = 90)
)
ON [PRIMARY]
GO