CREATE TABLE [dbo].[mt5_deals] (
  [Deal] [bigint] NOT NULL,
  [TIMESTAMP] [bigint] NOT NULL,
  [ExternalID] [nvarchar](32) NOT NULL,
  [Login] [bigint] NOT NULL,
  [Dealer] [bigint] NOT NULL,
  [Order] [bigint] NOT NULL,
  [Action] [int] NOT NULL,
  [Entry] [int] NOT NULL,
  [Reason] [int] NOT NULL,
  [Digits] [int] NOT NULL,
  [DigitsCurrency] [int] NOT NULL,
  [ContractSize] [float] NOT NULL,
  [Time] [datetime] NOT NULL,
  [Symbol] [nvarchar](32) NOT NULL,
  [Price] [float] NOT NULL,
  [Volume] [bigint] NOT NULL,
  [Profit] [float] NOT NULL,
  [Storage] [float] NOT NULL,
  [Commission] [float] NOT NULL,
  [RateProfit] [float] NOT NULL,
  [RateMargin] [float] NOT NULL,
  [ExpertID] [bigint] NOT NULL,
  [PositionID] [bigint] NOT NULL,
  [Comment] [nvarchar](32) NOT NULL,
  [ProfitRaw] [float] NOT NULL,
  [PricePosition] [float] NOT NULL,
  [VolumeClosed] [bigint] NOT NULL,
  [TickValue] [float] NOT NULL,
  [TickSize] [float] NOT NULL,
  [Flags] [bigint] NOT NULL,
  [Gateway] [nvarchar](16) NOT NULL,
  [PriceGateway] [float] NOT NULL,
  CONSTRAINT [PK_mt5_deals] PRIMARY KEY CLUSTERED ([Deal]) WITH (FILLFACTOR = 90)
)
ON [PRIMARY]
GO